Ma:
  -
    name: maperiod
    type: int
    min: 10
    max: 31
    step: 1

MaCross:
  -
    name: fast_length
    type: int
    min: 1
    max: 11
    step: 5
  -
    name: slow_length
    type: int
    min: 25
    max: 35
    step: 5